INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (1, 'Ail', 0.250, 1.99, 7.96, 'Condiments', 1, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (2, 'Carottes', 1.00, 2.88, 2.88, 'Légumes Frais', 1, 4);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (3, 'Celeri Rave', 0.75, 2.99, 3.99, 'Légumes Frais', 10, 3);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (4, 'Chou Rouge', 1.3, 4.28, 2.99, 'Légumes Frais', 10, 2);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (5, 'Chou Vert', 1.3, 3.93, 3.28, 'Légumes Frais', 10, 2);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (6, 'Ciboulette fraîche', 0.02, 1.44, 72.00, 'Herbes aromatiques', 1, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (7, 'Citron jaune', 0.5, 2.23, 4.46, 'Fruits Frais', 1, 4);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (8, 'Clémentine', 0.50, 3.99, 3.99, 'Fruits Frais', 11, 3);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (9, 'Courge butternut', 1.00, 3.95, 3.95, 'Légumes Frais', 6, 10);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (10, 'Endives', 1.00, 2.97, 2.97, 'Légumes Frais', 10, 4);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (11, 'Kiwis', 0.50, 4.65, 9.30, 'Fruits Frais', 10, 4);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (12, 'Laitue iceberg', 0.5, 2.50, 5.00, 'Salades', 3, 11);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (13, 'Laurier sec', 0.03, 1.57, 52.33, 'Herbes aromatiques', 1, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (14, 'Navet', 0.50, 2.94, 5.88, 'Légumes Frais', 10, 5);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (15, 'Oignon botte', 0.15, 2.96, 19.73, 'Condiments', 1, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (16, 'Oignon jaune', 0.500, 2.23, 4.46, 'Condiments', 1, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (17, 'Oignon rouge', 0.500, 3.64, 7.28, 'Condiments', 1, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (18, 'Orange', 0.650, 2.58, 3.97, 'Fruits Frais', 11, 5);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (19, 'Panais', 0.800, 4.39, 4.99, 'Légumes Frais', 1, 3);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (20, 'Persil frisé', 0.150, 2.70, 18.0, 'Herbes aromatiques', 1, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (21, 'Poires Louise', 0.800, 4.31, 4.90, 'Fruits Frais', 1, 11);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (22, 'Poireaux entiers', 1, 4.82, 4.82, 'Légumes Frais', 1, 8);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (23, 'Pommes Canada Grise', 0.750, 4.04, 4.90, 'Fruits Frais', 1, 4);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (24, 'Pommes Chanteclerc', 0.850, 4.67, 4.99, 'Fruits Frais', 5, 8);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (25, 'Pommes de terre blanches' , 2.5, 4.99, 2.00, 'Légumes Frais', 1, 6);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (26, 'Pommes de terre rouges', 2.5, 4.99, 2.00, 'Légumes Frais', 7, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (27, 'Pomme Golden', 2, 3.99, 2.00, 'Fruits Frais', 9, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (28, 'Salade Batavia', 1, 1.68, 4.20, 'Salades', 1, 5);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (29, 'Salade coeur de romaine', 2, 4.40, 6.29, 'Salades', 6, 12);
INSERT INTO ArticlePanier(id, nom, quantiteVendue, prix, prixKilo, categorie, debutSaison, finSaison) VALUES (30, 'Thym sec', 0.030, 1.57, 52.33, 'Herbes aromatiques', 1, 12);
